version: 2

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 10
    - title: Builds
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 20
    - title: etc
      order: 30
  filters:
    exclude:
      - '^.*?chore(\([[:word:]]+\))??!?:.+$'
      - '^.*?docs(\([[:word:]]+\))??!?:.+$'
      - '^.*?test(\([[:word:]]+\))??!?:.+$'
      - '^.*?ci(\([[:word:]]+\))??!?:.+$'

release:
  prerelease: auto
  footer: |
    {{ if and .Tag .PreviousTag }}
      **Commit history**: [{{ .PreviousTag }}...{{ .Tag }}]({{ .GitURL }}/compare/{{ .Tag }}...{{ .PreviousTag }})
    {{ else if .PreviousTag }}
      **Commit history**: [{{ .PreviousTag }}...{{ .ShortCommit }}]({{ .GitURL }}/compare/{{ .Commit }}...{{ .PreviousTag }})
    {{ end }}
