name: build

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          # - macos-latest # apparently incompatible with open-policy-agent/setup-opa
          # - windows-latest # Windows slows GitHub Actions checks down too much
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod

      - uses: open-policy-agent/setup-opa@v2
        with:
          version: 0.48

      - name: Build
        run: make ci
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.*

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./coverage.out
          flags: ${{ runner.os }}
